import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";

test(
  "additive tables preserve old inserts and save new answers privately and atomically",
  { skip: !process.env.REVUC_TEST_CONTAINER },
  () => {
    const container = process.env.REVUC_TEST_CONTAINER!;
    const database = "revuc_interest_forms_test";
    // Fixed disposable database only. No connection string or production database is accepted.
    const existing = execFileSync(
      "docker",
      [
        "exec",
        container,
        "psql",
        "-U",
        "revuc",
        "-d",
        "postgres",
        "-Atc",
        "select 1 from pg_database where datname='revuc_interest_forms_test'",
      ],
      { encoding: "utf8" },
    );
    if (!existing.trim())
      execFileSync("docker", ["exec", container, "createdb", "-U", "revuc", database]);
    const run = (query: string) =>
      execFileSync(
        "docker",
        [
          "exec",
          "-i",
          container,
          "psql",
          "-U",
          "revuc",
          "-d",
          database,
          "-v",
          "ON_ERROR_STOP=1",
          "-At",
        ],
        { input: query, encoding: "utf8" },
      );
    run(
      `
+do $$ begin
+  if not exists(select 1 from pg_roles where rolname='anon') then create role anon; end if;
+  if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated; end if;
+  if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role bypassrls; end if;
+end $$;
+create schema if not exists storage;
+create table if not exists storage.buckets(id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
+create table if not exists public.hacker_interest(id bigint generated by default as identity primary key, first_name text not null, last_name text not null, age text not null, phone text not null, email text not null, school text not null, level_of_study text not null, other_level_of_study text, country text not null, mlh_coc boolean not null, mlh_sharing boolean not null, mlh_emails boolean not null, created_at timestamptz default now());
+create table if not exists public.judge_mentor_interest(id bigint generated by default as identity primary key, full_name text not null, email text not null, linkedin_url text not null, phone text not null, organization text not null, job_title text not null, expertise_areas text, roles text, availability text not null, special_requirements text, expectations text, additional_info text, created_at timestamptz default now());
+create table if not exists public.sponsor_interest(id bigint generated by default as identity primary key, contact_name text not null, email text not null, organisation text not null, sponsorship_level text not null, primary_goal text not null, side_events text, additional_info text, created_at timestamptz default now());
+alter table public.hacker_interest enable row level security;
+alter table public.judge_mentor_interest enable row level security;
+alter table public.sponsor_interest enable row level security;
+grant usage on schema public to anon;
+grant insert on public.hacker_interest, public.judge_mentor_interest, public.sponsor_interest to anon;
+grant usage on all sequences in schema public to anon;
+do $$ begin
+  if not exists(select 1 from pg_policies where tablename='hacker_interest') then create policy "legacy insert" on public.hacker_interest for insert to public with check(true); end if;
+  if not exists(select 1 from pg_policies where tablename='judge_mentor_interest') then create policy "legacy insert" on public.judge_mentor_interest for insert to public with check(true); end if;
+  if not exists(select 1 from pg_policies where tablename='sponsor_interest') then create policy "legacy insert" on public.sponsor_interest for insert to public with check(true); end if;
+end $$;
+`.replace(/^\+/gm, ""),
    );
    const migration = readFileSync("supabase/interest-form-additions.sql", "utf8");
    run(migration);
    run(migration); // Safe reviewed setup can be re-applied.
    const output = run(
      `begin;
+set local role anon;
+insert into public.hacker_interest(id,first_name,last_name,age,phone,email,school,level_of_study,country,mlh_coc,mlh_sharing,mlh_emails) values(91001,'Old','Form','13','513-555-0123','old@example.test','Example','Prefer not to answer','United States',true,true,false);
+insert into public.hacker_interest(id,first_name,last_name,age,phone,email,school,level_of_study,country,mlh_coc,mlh_sharing,mlh_emails,extra_data,resume_path) values(91002,'New','Form','20','+15135550123','new@example.test','Example','Undergraduate University (3+ year)','United States',true,true,false,'{"major":"Computer Science","sponsorResumeConsent":true,"sponsorContactConsent":false}','revuc-2027/11111111-1111-4111-8111-111111111111.pdf');
+insert into public.judge_mentor_interest(id,full_name,email,linkedin_url,phone,organization,job_title,roles,availability) values(91001,'Old Judge','oldjudge@example.test','','+15135550123','Example','Engineer','Judge','Yes');
+insert into public.judge_mentor_interest(id,full_name,email,linkedin_url,phone,organization,job_title,roles,availability,extra_data) values(91002,'New Judge','judge@example.test','','+15135550123','Example','Engineer','Judge','Yes','{"conflicts":"None"}');
+insert into public.sponsor_interest(id,contact_name,email,organisation,sponsorship_level,primary_goal) values(91001,'Old Sponsor','oldsponsor@example.test','Example','Silver - ~$1k-3k','Recruit Top Talent');
+insert into public.sponsor_interest(id,contact_name,email,organisation,sponsorship_level,primary_goal,extra_data) values(91002,'New Sponsor','sponsor@example.test','Example','Silver - ~$1k-3k','Recruit Top Talent','{"budgetRange":"2000"}');
+reset role;
+do $$ begin
+  if (select count(*) from public.hacker_interest_details) <> 1 then raise exception 'Legacy hacker insert created details or new details missing'; end if;
+  if (select answers->>'major' from public.hacker_interest_details where interest_id=91002) <> 'Computer Science' then raise exception 'Hacker answer lost'; end if;
+  if (select resume_path from public.hacker_interest_details where interest_id=91002) is null then raise exception 'Resume path lost'; end if;
+  if (select count(*) from public.judge_mentor_interest_details) <> 1 then raise exception 'Judge answers lost'; end if;
+  if (select count(*) from public.sponsor_interest_details) <> 1 then raise exception 'Sponsor answers lost'; end if;
+  if exists(select 1 from pg_class where relname in ('hacker_interest_details','judge_mentor_interest_details','sponsor_interest_details') and not relrowsecurity) then raise exception 'Missing RLS'; end if;
+  if has_function_privilege('anon','registration_private.save_interest_details()','execute') then raise exception 'Public function execution'; end if;
+  if has_table_privilege('anon','public.hacker_interest_details','select,insert,update,delete') then raise exception 'Public details privilege'; end if;
+  if (select public from storage.buckets where id='revuc-2027-resumes') then raise exception 'Public resume bucket'; end if;
+end $$;
+-- A failed details write must roll back its parent interest insert too.
+alter table public.hacker_interest_details add constraint test_reject_answers check(answers->>'major' <> 'reject');
+do $$ begin
+  begin
+    insert into public.hacker_interest(id,first_name,last_name,age,phone,email,school,level_of_study,country,mlh_coc,mlh_sharing,mlh_emails,extra_data) values(91003,'Fail','Form','20','+15135550123','fail@example.test','Example','Other','United States',true,true,false,'{"major":"reject"}');
+    raise exception 'Expected details failure';
+  exception when check_violation then null; end;
+  if exists(select 1 from public.hacker_interest where id=91003) then raise exception 'Partial submission persisted'; end if;
+end $$;
+select 'compatibility-and-privacy-passed';
+rollback;
+`.replace(/^\+/gm, ""),
    );
    assert.match(output, /compatibility-and-privacy-passed/);
  },
);
